[tool.black]
line-length = 99
target-version = ["py38", "py39", "py310", "py311"]
exclude = '''
/(
    \.git|.venv
)/
'''

[tool.isort]
profile = "black"
float_to_top = true
skip_glob = ".venv"

[tool.poetry]
name = "sqlalchemy-to-json-schema"
version = "0.1.0"
description = "Convert SQLAlchemy models to JSON Schema definitions"
repository = "https://github.com/expobrain/sqlalchemy-to-json-schema"
authors = ["Daniele Esposti <daniele.esposti@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "sqlalchemy_to_json_schema" }]

[tool.poetry.dependencies]
python = "^3.8,<3.12"
sqlalchemy = "<2"
jsonschema = ">=4.17.3"
isodate = ">=0.6.1"
pytz = ">=2023.3"
dictknife = ">=0.7.2"
python-dateutil = ">=2.8"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
mypy = "^1.2"
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pytest-clarity = "^1.0.1"
pytest-testmon = "^2.0.6"
pytest-timeout = "^2.1.0"
webob = "^1.8.7"
pyyaml = "^6.0"
ruamel-yaml = "^0.17.31"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
exclude = ".venv/"
check_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_subclassing_any = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true

[tool.pytest.ini_options]
timeout = 10

[tool.poetry.scripts]
sqlalchemy_to_json_schema = "sqlalchemy_to_json_schema.command.main:main"
